baseurl = "http://www.remkoduursma.com/blog"
relativeurls = true
languageCode = "en-us"
title = "The R is for Remko"
theme = "hugo-future-imperfect"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[author]
    name = "Remko Duursma"
	email = "remkoduursma@gmail.com"
	
[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
	
[[menu.main]]
    name = "Home"
    url = "http://www.remkoduursma.com"

[params]
    description = "Remko Duursma's Blog for everything R"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "Vs"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

