baseurl = "http://www.remkoduursma.com/blog/"
relativeurls = true
languageCode = "en-us"
paginate = 3
title = "The R is for Remko"
theme = "hugo-future-imperfect"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir = "c:/repos/remkoduursma.github.io/blog"

[author]
    name = "Remko Duursma"
	email = "remkoduursma@gmail.com"
	
[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
	
[[menu.main]]
    name = "Home"
    url = "http://www.remkoduursma.com"
	identifier = "fa fa-home-o"

[params]
    description = "Remko Duursma's Blog for everything R"
    navbarTitle = ""
	
	socialAppearAtTop    = true
    socialAppearAtBottom = true
	
    # set this to the section name if section is not post
    viewMorePostLink     = "/post"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[params.intro]
    header    = "The R is for Remko"

    paragraph = "Remko Duursma's blog with R tutorials, package development, and data analysis."

    about     = "Remko Duursma is a senior lecturer at the Hawkesbury Institute for the Environment."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/logo.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    imperfect = true
    width     = ""
    alt       = "Remko"
	
# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2


# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    bitbucket       = "remkoduursma"
    github          = "remkoduursma"
	
